### PR TITLE
fix(build): Export ipfsApi global in browser build

### LINKED ISSUE #119: window.ipfsApi undefined in browser
Re docs: 
> Make the ipfsapi.min.js available through your server and load it using a normal \<script\> tag, this will export the ipfsAPI constructor on the window object, such that...

However, I am seeing `console.log(window.ipfsAPI)    // undefined`

Is documentation up to date for in-browser usage? I am trying to test out https://github.com/ipfs/js-ipfs-api/issues/55#issuecomment-136934361

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Closes #119

### CODE REVIEW

File: tasks/build.js [hunk 1]
```diff
@@ -9,7 +9,8 @@ var $ = require('gulp-load-plugins')()
 function getBrowserify () {
   return browserify({
     entries: ['./src/index.js'],
-    debug: true
+    debug: true,
+    standalone: 'ipfsApi'
```
Comment (diasdavid) [inline tasks/build.js]: We've been promising `ipfsAPI`, if there is a preference, can we have both?

Comment (Dignifiedquire) [inline tasks/build.js]: uups, just a typo on my side, happy to do `ipfsAPI`

**Comment by diasdavid** [comment]
LGTM :)
