### PR TITLE
Make url-add follow HTTP redirections

### LINKED ISSUE #513: addFromURL fails to follow redirections
```js
ipfs.util.addFromURL('http://covers.openlibrary.org/book/id/969165.jpg')
```
will return the hash of an empty file (`QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH` instead of the expected `QmaL9zy7YUfvWmtD5ZXp42buP7P4xmZJWFkm78p8FJqgjg`) because [`request.js`](https://github.com/ipfs/js-ipfs-api/blob/0295a5a1ad9754f83224d5a236fed94f5c7b202d/src/request.js) doesn't follow redirections

### PR DESCRIPTION
**Pull request by maxlath**
fix #513 

That's the shortest path I found to solve this issue, but different solutions could be considered:

* delegating redirection handling to [`request.js`](https://github.com/ipfs/js-ipfs-api/blob/0295a5a1ad9754f83224d5a236fed94f5c7b202d/src/request.js)
* reintegrating a HTTP request library that handles it, but I guess you had your reasons to remove `wreck`

### CODE REVIEW

File: src/api/util/url-add.js [hunk 1]
```diff
@@ -22,28 +22,41 @@ module.exports = (send) => {
...
+const requestWithRedirect = (url, opts, send, callback) => {
+  request(parseUrl(url).protocol)(url, (res) => {
+    res.once('error', callback)
+    if (res.statusCode >= 400) {
+      return callback(new Error(`Failed to download with ${res.statusCode}`))
+    }
 
+    const redirection = res.headers.location
+
+    if (redirection) {
```
Comment (dignifiedquire) [inline src/api/util/url-add.js]: This should also check for the right redirection header.

**Comment by dignifiedquire** [comment]
Why is this not part of node core...

File: src/api/util/url-add.js (hunk 1 above)
Comment (maxlath) [inline src/api/util/url-add.js]: Which header is that if not `location`? That's the header in the [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3) and that seem to be [used by the request module too](https://github.com/request/request/blob/f009af231412fe8fee4ab5dd24d24781fd731fc3/lib/redirect.js#L50).

Comment (dignifiedquire) [inline src/api/util/url-add.js]: I'm sorry, I meant the status code

Comment (maxlath) [inline src/api/util/url-add.js]: Indeed. I'm adding a commit to cover that

Comment (maxlath) [inline src/api/util/url-add.js]: fix 4821ac4

**Comment by diasdavid** [comment]
@maxlath mind doing a rebase of master into this branch?

**Comment by maxlath** [comment]
@diasdavid rebase done! plus, I added a test 78c0537

**Comment by diasdavid** [comment]
@maxlath mind fixing lint? Looks like that is the last step to get this done :)

**Comment by maxlath** [comment]
@diasdavid done!

**Comment by diasdavid** [comment]
awesome, thanks @maxlath :D
